### ISSUE TITLE
## 🚨 `--expose` regression in Action-Server ≥ 2.11.0 (RCC 20.x)

### ISSUE THREAD

**Issue by joshyorko** [joshyorko/actions#3]
### Summary
Starting with **action-server 2.11.0**, the server no longer opens a public tunnel when launched with `--expose`.  
Verbose output shows RCC 20.x raising `unknown command "internal" for "rcc"`, while the same action package works flawlessly with action-server ≤ 2.10.0 (bundling RCC 19.x).

### Reproduction steps

```bash
# clean slate
rm -rf ~/.sema4ai

# any Action-Server ≤ 2.10.0  ✅ works
curl -LO https://cdn.sema4.ai/action-server/releases/2.10.0/linux64/action-server
chmod +x action-server
./action-server start --expose  # 🌍 tunnel appears

# same machine, Action-Server ≥ 2.11.0  ❌ fails
curl -LO https://cdn.sema4.ai/action-server/releases/2.11.0/linux64/action-server
chmod +x action-server
./action-server start --expose --verbose
# → hangs after local startup, key log line:
# Error: unknown command "internal" for "rcc" (rcc v20.1.1)
````

### Action package used

`package.yaml` (pinned versions):

```yaml
name: home-lab-actions
description: Action package description
version: 0.0.1
spec-version: v2

dependencies:
  conda-forge:
    - python=3.10.14
    - uv=0.6.3
  pypi:
    - sema4ai-actions=1.3.13
    - paramiko=3.5.1
    - python-dotenv=1.1.1
    - kubernetes=33.1.0

packaging:
  exclude:
    - ./.git/**
    # …truncated…
```

*Same package works on 2.6.0 → 2.10.0, fails on 2.11.0 & 2.12.1.*

### Good / bad matrix

| Action-Server       | Bundled RCC | Result                                |
| ------------------- | ----------- | ------------------------------------- |
| 2.6.0               | 19.0.2      | ✅ PASS                                |
| 2.7.0               | 19.0.2      | ✅ PASS                                |
| 2.8.0               | 19.0.2      | ✅ PASS                                |
| 2.9.0               | 19.0.2      | ✅ PASS                                |
| 2.10.0              | 19.0.2      | ✅ PASS                                |
| **2.11.0**          | **20.1.1**  | ❌ FAIL *(“unknown command internal”)* |
| **2.12.0 / 2.12.1** | **20.1.1**  | ❌ FAIL                                |

### Minimal verbose log excerpt (2.11.0)

```
Error: unknown command "internal" for "rcc"
[rcc v20.1.1] unknown command "internal" …
Process … exit status 1, command: …rcc-20.1.1 [internal env --label before]
Activation failure: exit status 1
```

### Temporary work-arounds

1. **Stay on action-server ≤ 2.10.0**, or
2. Keep latest server but force RCC 19.x:

```bash
export RCC_VERSION=v19.0.2
action-server start --expose
```

### Suspected root-cause

Action-Server still invokes the hidden `rcc internal env --label before/after` helpers, which were removed in **RCC 20.x** (first bundled with 2.11.0). Re-adding the helper or switching to a supported activation API should restore `--expose`.

### Environment

* OS   : Pop!\_OS 22.04 (Ubuntu 22.04 LTS) x86\_64
* Python : packaged via RCC holotree (3.10.14)
* sema4ai-actions (PyPI) : **1.3.13**

---

Please let me know if I can provide additional logs or test a patch 🙌

```
```
